name: Docker Build and Push

on:
  push:
    branches:
      - master # switch in master from main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SHA7: "${GITHUB_SHA:0:7}"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mariuspnct/resistorapp:${SHA7} .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image to Docker Hub
        run: docker push mariuspnct/resistorapp:${SHA7}"

  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: resistor_color_code
          image: docker.io/mariuspnct/resistorapp:${SHA7}

      - name: debug
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: debug-Display Task Definition
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: resistor_color_code-service
          cluster: resistor_color_code-cluster
          wait-for-service-stability: true
