name: Docker Build and Push

on:
  push:
    branches:
      - master # switch in master from main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t mariuspnct/resistorapp:latest .

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Tag Docker image
        run: docker tag mariuspnct/resistorapp:latest mariuspnct/resistorapp:latest

      - name: Push Docker image to Docker Hub
        run: docker push mariuspnct/resistorapp:latest
